Lecture3 c
SehedaOleh/GL_EmbeddedProCamp pull request #3
Opened 2018-09-24 22:17 UTC by SehedaOleh

In general I try to accumulate all previous notes and create this task more precise. Could you please review it and send me some feedback. thanks a lot.

2018-10-02 10:23 UTC, rikorsev requested changes

2018-10-02 10:23 UTC, rikorsev commented on Lecture_3/L3_ex1.c
> +    char digital_string[256] = { };
It is good that you have initialized the array, but I would prefer that you do it in more explicit way:
char digital_string[256] = { 0 };

2018-10-02 10:23 UTC, rikorsev commented on Lecture_3/L3_ex1.c
> +    scanf( "%s" , &initial_string );
Here is two mistakes:
1) scanf is not the best function to get a string, because if you write string like:
"my numbers are 11 and 56"
**initial_string** would contains only "my" string.
in this case is much more better to use **gets** function

2) **initial_string** - is already a pointer, so you haven't to pass to the function address of a pointer but only address that this pointer stores.
in your case the code is works but if you allocate **initial_string** like this:
char initial_string = malloc(256);
then address of pointer and address that the pointer are contains would be different and it could lead to unpredictable consequences.
The proper way  here is:
scanf( "%s" , initial_string );

2018-10-02 10:23 UTC, rikorsev commented on Lecture_3/L3_ex2.c
> +#define array_length 25
Usual C code convention says that all macroses should be written with upper case like this:
#define ARRAY_LENGTH 25

2018-10-02 10:23 UTC, rikorsev commented on Lecture_3/L3_ex2.c
> +
**rand** function is declared in **stdlib.h** header. You forgot to add it here.

2018-10-02 10:23 UTC, rikorsev commented on Lecture_3/L3_ex2.c
> +    max_number = digit_array[0];
here is unnecessary assignment

2018-10-02 10:23 UTC, rikorsev commented on Lecture_3/ListLib.h
> +/***************************************
Never put function implementation in header files (.h)! Put here only reference to function.
If you try to include **ListLib.h** in one more file it will lead to errors on linking stage, because linker would treat that program has two same functions **ListAdd** for example. Also, it is good to protect you code from double including like this:
#pragma once
or 
#ifndef LIST_LIB_H
#define LIST_LIB_H
/* ...header content... */
#endif

2018-10-02 10:23 UTC, rikorsev commented on Lecture_3/L3_ex3.c
> +    if (list_init == NULL)
Good! You check result of malloc function!

2018-10-02 10:23 UTC, rikorsev commented on Lecture_3/ListLib.h
> +    struct link_list *new_element;
it is better to call this member as **next** or **next element**

2018-10-02 10:23 UTC, rikorsev commented on Lecture_3/ListLib.h
> +    current_list -> new_element = malloc(sizeof(link_list_t));
And here you don't check result of malloc :(

2018-10-02 10:23 UTC, rikorsev commented on Lecture_3/ListLib.h
> +void ListShows (link_list_t *ptr_list)
Why do you split showing in two different loops?

2018-10-02 10:23 UTC, rikorsev commented on Lecture_3/ListLib.h
> +    value_d = current_list -> digit;
what is the purpose of this variables and this assignment?

2018-10-04 21:13 UTC, SehedaOleh commented on Lecture_3/ListLib.h
> +void ListShows (link_list_t *ptr_list)
It was done only for visual reason. I can use only one loop for this.

2018-10-06 20:32 UTC, SehedaOleh commented
Hello Alexander. I updated task according to yours comment.

2018-10-17 09:54 UTC, rikorsev approved these changes
In general pool request looks more/less ok. Just few blots here. Clear it and you could merge the pull request.

2018-10-17 09:54 UTC, rikorsev commented on Lecture_3/L3_ex1.c
> +}
Good.

2018-10-17 09:54 UTC, rikorsev commented on Lecture_3/L3_ex2.c
> +}
Good

2018-10-17 09:54 UTC, rikorsev commented on Lecture_3/L3_ex3.c
> +    /* * * * * * debug * * * * * * * * * * * * * * * * * *
If you need to hide some debug stuff it is better to use the following construction:
#ifdef DEBUG
/* some implementation */
#endif

2018-10-17 09:54 UTC, rikorsev commented on Lecture_3/ListLib.c
> +void ListShows (link_list_t *ptr_list)
I still don't understand why do you need two separate **while** loops here?

2018-10-17 09:54 UTC, rikorsev commented on Lecture_3/ListLib.c
> +    //int value_n;
It is bad idea to leave commented code in the files

2018-11-03 19:42 UTC, merged