Lecture4 c
SehedaOleh/GL_EmbeddedProCamp pull request #4
Opened 2018-09-26 22:21 UTC by SehedaOleh

Tasks for Lecture 4 done. Could you please review them? Thanks a  lot Oleh.

2018-10-11 10:18 UTC, rikorsev requested changes

2018-10-11 10:18 UTC, rikorsev commented on Lecture4_C/L4_ex1.c
> +    str_temp = (char*)malloc(sizeof(char)*string_length);
malloc returns void*. in this case explicit cast is unnecessary.

2018-10-11 10:18 UTC, rikorsev commented on Lecture4_C/L4_ex1.c
> +    length = sizeof (string_to_copy);
This function will not work properly, because in this case sizeof will return size of pointer but not size of string.
It is better to use **strlen** functions or specify size to copy as function argument.

2018-10-11 10:18 UTC, rikorsev commented on Lecture4_C/L4_ex4.c
> +    result_of_test_function = test_func(p_f1, number_1, number_2);
It is unnecessary to use pointer to pass function as argument you could do it directly:
result_of_test_function = test_func(add, number_1, number_2);

2018-10-11 10:18 UTC, rikorsev commented on Lecture4_C/Queue_lib.h
> +int8_t start_queue_index = -1;  // start index of the queue
If it is library header it would be better to specify queue type and use it in the code.

2018-10-11 10:18 UTC, rikorsev commented on Lecture4_C/Stack_lib.h
> +stack_t *stack_pointer; // creation of the init stack pointer.
here is only one stack pointer available. What if you need more?

2018-10-15 15:31 UTC, SehedaOleh commented on Lecture4_C/L4_ex1.c
> +    length = sizeof (string_to_copy);
I don't know why it didn't showed but this one has been already implement.

2018-11-04 11:17 UTC, SehedaOleh commented
Can I merge this branch into master?

2019-11-20 21:03 UTC, closed without merging